### PR TITLE
Code and Javadoc cleanup

### PR DESCRIPTION
**Pull request by dgiagio**
- Code cleanup such as removing extra semicolon, redundant or unused variables, incorrect exception throw specifications and unnecessary boxing for primitive integer type.
- Add missing Javadoc and remove incorrect ones.

### CODE REVIEW

**Comment by lucidd** [comment]
Haha seems like we had the same idea but since you were faster can you include the deletion of [this](https://github.com/SUSE/saltstack-netapi-client-java/blob/master/src/main/java/com/suse/saltstack/netapi/client/SaltStackJDKConnection.java#L51) documentation of an outdated parameter. :smile:

**Comment by dgiagio** [comment]
@lucidd This is already in the PR. :-)

**Comment by lucidd** [comment]
Oh you're right my bad didn't see it at first. :)

**Comment by moio** [comment]
Merge-Just-Do-It (TM).

Thanks a lot.

**Pull request merged**
