### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by dgiagio**
- Add final modifier where appropriate.
- Removed unneded ```throws SaltStackException``` from ```*Async``` methods.

### CODE REVIEW

**Comment by isbm** [comment]
LGTM

**Comment by dgiagio** [comment]
@renner Good catch, thanks! Fixed.

**Comment by renner** [comment]
Thanks for fixing up, patch can be merged now from my perspective.

**Comment by moio** [comment]
Good, merged, thanks!

**Pull request merged**
