### PR TITLE
Switch Pkg.Info to use ZonedTimeDate

### PR DESCRIPTION
**Pull request by lucidd**
This changes the `TimeDate` of `Pkg.Info` to include timezone information to reflect @isbm recent changes in salt.

### CODE REVIEW

**Comment by isbm** [comment]
@lucidd Unit test? :chicken:

**Comment by lucidd** [comment]
@isbm Works on my machine :stuck_out_tongue:  :poultry_leg:

**Comment by isbm** [comment]
@lucidd Jenkins doesn't believe you. :-) Please add a unit test for this.

**Comment by lucidd** [comment]
@isbm @renner i added a unit test for the `pkg.info_installed` call which includes parsing and checking the timezone. Also since this is the first unit test for the call API it can serve as example how to write unit tests for the rest.

**Comment by isbm** [comment]
:kiss: 

As of me, merge it, @lucidd

**Comment by AdamMajer** [comment]
Seems you can remove the LocalDateTime parser - it's not used anymore.

Looks good. :+1:

**Comment by lucidd** [comment]
@AdamMajer i left it there because we will need it in the future since the plan is to long term move away from `Date` and use only the java 8 equivalents.

**Pull request merged**
